/**
 * This class is generated by jOOQ
 */
package com.vienna.question.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.joda.time.DateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TType implements Serializable {

    private static final long serialVersionUID = -711652794;

    private Integer  id;
    private String   name;
    private String   descriptions;
    private Integer  number;
    private DateTime created;
    private DateTime updated;
    private Boolean  status;

    public TType() {}

    public TType(TType value) {
        this.id = value.id;
        this.name = value.name;
        this.descriptions = value.descriptions;
        this.number = value.number;
        this.created = value.created;
        this.updated = value.updated;
        this.status = value.status;
    }

    public TType(
        Integer  id,
        String   name,
        String   descriptions,
        Integer  number,
        DateTime created,
        DateTime updated,
        Boolean  status
    ) {
        this.id = id;
        this.name = name;
        this.descriptions = descriptions;
        this.number = number;
        this.created = created;
        this.updated = updated;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public TType setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public TType setName(String name) {
        this.name = name;
        return this;
    }

    public String getDescriptions() {
        return this.descriptions;
    }

    public TType setDescriptions(String descriptions) {
        this.descriptions = descriptions;
        return this;
    }

    public Integer getNumber() {
        return this.number;
    }

    public TType setNumber(Integer number) {
        this.number = number;
        return this;
    }

    public DateTime getCreated() {
        return this.created;
    }

    public TType setCreated(DateTime created) {
        this.created = created;
        return this;
    }

    public DateTime getUpdated() {
        return this.updated;
    }

    public TType setUpdated(DateTime updated) {
        this.updated = updated;
        return this;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public TType setStatus(Boolean status) {
        this.status = status;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TType (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(descriptions);
        sb.append(", ").append(number);
        sb.append(", ").append(created);
        sb.append(", ").append(updated);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
