/**
 * This class is generated by jOOQ
 */
package com.vienna.domain;


import com.vienna.domain.tables.TQuestion;
import com.vienna.domain.tables.TType;
import com.vienna.domain.tables.TUser;
import com.vienna.domain.tables.records.TQuestionRecord;
import com.vienna.domain.tables.records.TTypeRecord;
import com.vienna.domain.tables.records.TUserRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>vienna</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TQuestionRecord, Integer> IDENTITY_T_QUESTION = Identities0.IDENTITY_T_QUESTION;
    public static final Identity<TTypeRecord, Integer> IDENTITY_T_TYPE = Identities0.IDENTITY_T_TYPE;
    public static final Identity<TUserRecord, Integer> IDENTITY_T_USER = Identities0.IDENTITY_T_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TQuestionRecord> KEY_T_QUESTION_PRIMARY = UniqueKeys0.KEY_T_QUESTION_PRIMARY;
    public static final UniqueKey<TTypeRecord> KEY_T_TYPE_PRIMARY = UniqueKeys0.KEY_T_TYPE_PRIMARY;
    public static final UniqueKey<TUserRecord> KEY_T_USER_PRIMARY = UniqueKeys0.KEY_T_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<TQuestionRecord, Integer> IDENTITY_T_QUESTION = createIdentity(TQuestion.T_QUESTION, TQuestion.T_QUESTION.ID);
        public static Identity<TTypeRecord, Integer> IDENTITY_T_TYPE = createIdentity(TType.T_TYPE, TType.T_TYPE.ID);
        public static Identity<TUserRecord, Integer> IDENTITY_T_USER = createIdentity(TUser.T_USER, TUser.T_USER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<TQuestionRecord> KEY_T_QUESTION_PRIMARY = createUniqueKey(TQuestion.T_QUESTION, "KEY_t_question_PRIMARY", TQuestion.T_QUESTION.ID);
        public static final UniqueKey<TTypeRecord> KEY_T_TYPE_PRIMARY = createUniqueKey(TType.T_TYPE, "KEY_t_type_PRIMARY", TType.T_TYPE.ID);
        public static final UniqueKey<TUserRecord> KEY_T_USER_PRIMARY = createUniqueKey(TUser.T_USER, "KEY_t_user_PRIMARY", TUser.T_USER.ID);
    }
}
