/**
 * This class is generated by jOOQ
 */
package com.vienna.domain;


import com.vienna.domain.tables.TQuestion;
import com.vienna.domain.tables.TType;
import com.vienna.domain.tables.TUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in vienna
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>vienna.t_question</code>.
     */
    public static final TQuestion T_QUESTION = com.vienna.domain.tables.TQuestion.T_QUESTION;

    /**
     * The table <code>vienna.t_type</code>.
     */
    public static final TType T_TYPE = com.vienna.domain.tables.TType.T_TYPE;

    /**
     * The table <code>vienna.t_user</code>.
     */
    public static final TUser T_USER = com.vienna.domain.tables.TUser.T_USER;
}
