/**
 * This class is generated by jOOQ
 */
package com.vienna.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.joda.time.DateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUser implements Serializable {

    private static final long serialVersionUID = 1865639486;

    private Integer  id;
    private String   password;
    private String   name;
    private String   phone;
    private String   email;
    private DateTime created;
    private DateTime updated;
    private Boolean  status;

    public TUser() {}

    public TUser(TUser value) {
        this.id = value.id;
        this.password = value.password;
        this.name = value.name;
        this.phone = value.phone;
        this.email = value.email;
        this.created = value.created;
        this.updated = value.updated;
        this.status = value.status;
    }

    public TUser(
        Integer  id,
        String   password,
        String   name,
        String   phone,
        String   email,
        DateTime created,
        DateTime updated,
        Boolean  status
    ) {
        this.id = id;
        this.password = password;
        this.name = name;
        this.phone = phone;
        this.email = email;
        this.created = created;
        this.updated = updated;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public TUser setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getPassword() {
        return this.password;
    }

    public TUser setPassword(String password) {
        this.password = password;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public TUser setName(String name) {
        this.name = name;
        return this;
    }

    public String getPhone() {
        return this.phone;
    }

    public TUser setPhone(String phone) {
        this.phone = phone;
        return this;
    }

    public String getEmail() {
        return this.email;
    }

    public TUser setEmail(String email) {
        this.email = email;
        return this;
    }

    public DateTime getCreated() {
        return this.created;
    }

    public TUser setCreated(DateTime created) {
        this.created = created;
        return this;
    }

    public DateTime getUpdated() {
        return this.updated;
    }

    public TUser setUpdated(DateTime updated) {
        this.updated = updated;
        return this;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public TUser setStatus(Boolean status) {
        this.status = status;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUser (");

        sb.append(id);
        sb.append(", ").append(password);
        sb.append(", ").append(name);
        sb.append(", ").append(phone);
        sb.append(", ").append(email);
        sb.append(", ").append(created);
        sb.append(", ").append(updated);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
