/**
 * This class is generated by jOOQ
 */
package com.vienna.question.domain.tables.records;


import com.vienna.question.domain.tables.TQuestion;

import javax.annotation.Generated;

import org.joda.time.DateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TQuestionRecord extends UpdatableRecordImpl<TQuestionRecord> implements Record9<Integer, Integer, Integer, String, String, String, DateTime, DateTime, Boolean> {

    private static final long serialVersionUID = 1329562313;

    /**
     * Setter for <code>vienna.t_question.ID</code>.  主键
     */
    public TQuestionRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_question.ID</code>.  主键
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vienna.t_question.TYPE_ID</code>. 问题类型
     */
    public TQuestionRecord setTypeId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_question.TYPE_ID</code>. 问题类型
     */
    public Integer getTypeId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>vienna.t_question.USER_ID</code>. 问题提交人
     */
    public TQuestionRecord setUserId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_question.USER_ID</code>. 问题提交人
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>vienna.t_question.QUESTION</code>. 问题描述
     */
    public TQuestionRecord setQuestion(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_question.QUESTION</code>. 问题描述
     */
    public String getQuestion() {
        return (String) get(3);
    }

    /**
     * Setter for <code>vienna.t_question.SOLVED</code>. 解决思路
     */
    public TQuestionRecord setSolved(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_question.SOLVED</code>. 解决思路
     */
    public String getSolved() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vienna.t_question.REFRERENCE</code>. 参考资料
     */
    public TQuestionRecord setRefrerence(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_question.REFRERENCE</code>. 参考资料
     */
    public String getRefrerence() {
        return (String) get(5);
    }

    /**
     * Setter for <code>vienna.t_question.CREATED</code>. 创建时间
     */
    public TQuestionRecord setCreated(DateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_question.CREATED</code>. 创建时间
     */
    public DateTime getCreated() {
        return (DateTime) get(6);
    }

    /**
     * Setter for <code>vienna.t_question.UPDATED</code>. 更新时间
     */
    public TQuestionRecord setUpdated(DateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_question.UPDATED</code>. 更新时间
     */
    public DateTime getUpdated() {
        return (DateTime) get(7);
    }

    /**
     * Setter for <code>vienna.t_question.STATUS</code>. 状态（1：正常，0：删除）
     */
    public TQuestionRecord setStatus(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_question.STATUS</code>. 状态（1：正常，0：删除）
     */
    public Boolean getStatus() {
        return (Boolean) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, String, String, String, DateTime, DateTime, Boolean> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, String, String, String, DateTime, DateTime, Boolean> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TQuestion.T_QUESTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TQuestion.T_QUESTION.TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TQuestion.T_QUESTION.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TQuestion.T_QUESTION.QUESTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TQuestion.T_QUESTION.SOLVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TQuestion.T_QUESTION.REFRERENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<DateTime> field7() {
        return TQuestion.T_QUESTION.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<DateTime> field8() {
        return TQuestion.T_QUESTION.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return TQuestion.T_QUESTION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getQuestion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSolved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRefrerence();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DateTime value7() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DateTime value8() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQuestionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQuestionRecord value2(Integer value) {
        setTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQuestionRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQuestionRecord value4(String value) {
        setQuestion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQuestionRecord value5(String value) {
        setSolved(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQuestionRecord value6(String value) {
        setRefrerence(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQuestionRecord value7(DateTime value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQuestionRecord value8(DateTime value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQuestionRecord value9(Boolean value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TQuestionRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, DateTime value7, DateTime value8, Boolean value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TQuestionRecord
     */
    public TQuestionRecord() {
        super(TQuestion.T_QUESTION);
    }

    /**
     * Create a detached, initialised TQuestionRecord
     */
    public TQuestionRecord(Integer id, Integer typeId, Integer userId, String question, String solved, String refrerence, DateTime created, DateTime updated, Boolean status) {
        super(TQuestion.T_QUESTION);

        set(0, id);
        set(1, typeId);
        set(2, userId);
        set(3, question);
        set(4, solved);
        set(5, refrerence);
        set(6, created);
        set(7, updated);
        set(8, status);
    }
}
