/**
 * This class is generated by jOOQ
 */
package com.vienna.question.domain.tables.records;


import com.vienna.question.domain.tables.TType;

import javax.annotation.Generated;

import org.joda.time.DateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTypeRecord extends UpdatableRecordImpl<TTypeRecord> implements Record7<Integer, String, String, Integer, DateTime, DateTime, Boolean> {

    private static final long serialVersionUID = -554234463;

    /**
     * Setter for <code>vienna.t_type.ID</code>. 主键id
     */
    public TTypeRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_type.ID</code>. 主键id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vienna.t_type.NAME</code>. 类型名称
     */
    public TTypeRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_type.NAME</code>. 类型名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vienna.t_type.DESCRIPTIONS</code>. 类型描述
     */
    public TTypeRecord setDescriptions(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_type.DESCRIPTIONS</code>. 类型描述
     */
    public String getDescriptions() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vienna.t_type.NUMBER</code>. 问题类型发生的数量
     */
    public TTypeRecord setNumber(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_type.NUMBER</code>. 问题类型发生的数量
     */
    public Integer getNumber() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>vienna.t_type.CREATED</code>. 创建时间
     */
    public TTypeRecord setCreated(DateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_type.CREATED</code>. 创建时间
     */
    public DateTime getCreated() {
        return (DateTime) get(4);
    }

    /**
     * Setter for <code>vienna.t_type.UPDATED</code>. 更新时间
     */
    public TTypeRecord setUpdated(DateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_type.UPDATED</code>. 更新时间
     */
    public DateTime getUpdated() {
        return (DateTime) get(5);
    }

    /**
     * Setter for <code>vienna.t_type.STATUS</code>. 状态（1：正常，0：删除）
     */
    public TTypeRecord setStatus(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_type.STATUS</code>. 状态（1：正常，0：删除）
     */
    public Boolean getStatus() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Integer, DateTime, DateTime, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Integer, DateTime, DateTime, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TType.T_TYPE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TType.T_TYPE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TType.T_TYPE.DESCRIPTIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TType.T_TYPE.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<DateTime> field5() {
        return TType.T_TYPE.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<DateTime> field6() {
        return TType.T_TYPE.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return TType.T_TYPE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescriptions();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DateTime value5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DateTime value6() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTypeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTypeRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTypeRecord value3(String value) {
        setDescriptions(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTypeRecord value4(Integer value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTypeRecord value5(DateTime value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTypeRecord value6(DateTime value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTypeRecord value7(Boolean value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTypeRecord values(Integer value1, String value2, String value3, Integer value4, DateTime value5, DateTime value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TTypeRecord
     */
    public TTypeRecord() {
        super(TType.T_TYPE);
    }

    /**
     * Create a detached, initialised TTypeRecord
     */
    public TTypeRecord(Integer id, String name, String descriptions, Integer number, DateTime created, DateTime updated, Boolean status) {
        super(TType.T_TYPE);

        set(0, id);
        set(1, name);
        set(2, descriptions);
        set(3, number);
        set(4, created);
        set(5, updated);
        set(6, status);
    }
}
