/**
 * This class is generated by jOOQ
 */
package com.vienna.question.domain.tables.records;


import com.vienna.question.domain.tables.TUser;

import javax.annotation.Generated;

import org.joda.time.DateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRecord extends UpdatableRecordImpl<TUserRecord> implements Record8<Integer, String, String, String, String, DateTime, DateTime, Boolean> {

    private static final long serialVersionUID = -1846961514;

    /**
     * Setter for <code>vienna.t_user.ID</code>. 主键id
     */
    public TUserRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_user.ID</code>. 主键id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vienna.t_user.PASSWORD</code>. 密码
     */
    public TUserRecord setPassword(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_user.PASSWORD</code>. 密码
     */
    public String getPassword() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vienna.t_user.NAME</code>. 用户名
     */
    public TUserRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_user.NAME</code>. 用户名
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vienna.t_user.PHONE</code>. 手机号码
     */
    public TUserRecord setPhone(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_user.PHONE</code>. 手机号码
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>vienna.t_user.EMAIL</code>. 电子邮箱
     */
    public TUserRecord setEmail(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_user.EMAIL</code>. 电子邮箱
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vienna.t_user.CREATED</code>. 创建时间
     */
    public TUserRecord setCreated(DateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_user.CREATED</code>. 创建时间
     */
    public DateTime getCreated() {
        return (DateTime) get(5);
    }

    /**
     * Setter for <code>vienna.t_user.UPDATED</code>. 更新时间
     */
    public TUserRecord setUpdated(DateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_user.UPDATED</code>. 更新时间
     */
    public DateTime getUpdated() {
        return (DateTime) get(6);
    }

    /**
     * Setter for <code>vienna.t_user.STATUS</code>.
     */
    public TUserRecord setStatus(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>vienna.t_user.STATUS</code>.
     */
    public Boolean getStatus() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, DateTime, DateTime, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, DateTime, DateTime, Boolean> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TUser.T_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TUser.T_USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TUser.T_USER.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TUser.T_USER.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TUser.T_USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<DateTime> field6() {
        return TUser.T_USER.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<DateTime> field7() {
        return TUser.T_USER.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return TUser.T_USER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DateTime value6() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DateTime value7() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value2(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value4(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value5(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value6(DateTime value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value7(DateTime value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value8(Boolean value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord values(Integer value1, String value2, String value3, String value4, String value5, DateTime value6, DateTime value7, Boolean value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TUserRecord
     */
    public TUserRecord() {
        super(TUser.T_USER);
    }

    /**
     * Create a detached, initialised TUserRecord
     */
    public TUserRecord(Integer id, String password, String name, String phone, String email, DateTime created, DateTime updated, Boolean status) {
        super(TUser.T_USER);

        set(0, id);
        set(1, password);
        set(2, name);
        set(3, phone);
        set(4, email);
        set(5, created);
        set(6, updated);
        set(7, status);
    }
}
